/*
 * Copyright 2026 University of Manitoba Robotics Team
 * Noah Reeder
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef ROS2_J1939_BABBLER_MSGS__TYPE_CONVERSION_HELPERS_HPP_
#define ROS2_J1939_BABBLER_MSGS__TYPE_CONVERSION_HELPERS_HPP_

#include "type_conversion.hpp"


#include <algorithm>
#include <memory>
#include <string>
#include <type_traits>
#include <unordered_map>

#include <cassert>
#include <cstdint>

#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/header.hpp>
#include <can_msgs/msg/frame.hpp>

namespace ros2_j1939_babbler_msgs
{
    /**
     * Need this to prevent compiler from automatically instantiating primary `populateRos`/`populateCan` template and
	 * hitting the static_assert
     * @tparam T dummy
     */
    template<typename T>
    struct dependent_false : std::false_type {};

    /**
     * Maps PGNs to ROS message types.
     * @tparam PGN J1939 PGN to look up
     */
    template<uint32_t PGN> struct pgn_ros_message_type_map;

    /**
     * Maps PGNs to CAN message types.
     * @tparam PGN J1939 PGN to look up
     */
    template<uint32_t PGN> struct pgn_can_message_type_map;

    /**
     * Maps ROS message types to the message type as a string.
     * @tparam MSG_TYPE ROS type to stringify
     */
    template<typename MSG_TYPE> struct message_type_name_map;

    /**
     * Maps PGNs to message lengths.
     * @tparam PGN J1939 PGN to look up
     */
    template<uint32_t PGN> struct pgn_dlc_map;

    // Default type conversion, throws a compile-time error because we are expecting template to be specialised for known messages
    /**
     * Fills a ROS message of the provided type using a map of J1939 signal names to their values.
     * If a message type not generated by ros2_j1939_babbler_msgs is provided, compilation will be blocked.
     * @tparam ROS_MSG_TYPE ROS message type to transcode to
     * @tparam CAN_MSG_TYPE C CAN message type to transcode from
     * @param ros_msg ROS message instance to populate
     * @param can_msg CAN message instance to transcode
     */
    template<typename ROS_MSG_TYPE, typename CAN_MSG_TYPE>
    void populateRos(ROS_MSG_TYPE& ros_msg, const CAN_MSG_TYPE& can_msg)
    {
        (void)ros_msg; // Make unused parameter warnings go away
        (void)can_msg;
        static_assert(dependent_false<ROS_MSG_TYPE>::value, "No type conversion was generated for the provided ROS message type");
    }

    /**
     * Fills a CAN message of the provided type using the contents of an instance of the associated ROS message.
     * If a message type not generated by ros2_j1939_babbler_msgs is provided, compilation will be blocked.
     * @tparam CAN_MSG_TYPE C CAN message type to transcode to
     * @tparam ROS_MSG_TYPE ROS message type to transcode from
     * @param can_msg CAN message instance to fill
     * @param ros_msg ROS message instance to transcode
     */
    template<typename CAN_MSG_TYPE, typename ROS_MSG_TYPE>
    void populateCan(CAN_MSG_TYPE& can_msg, const ROS_MSG_TYPE& ros_msg)
    {
        (void)can_msg; // Make unused parameter warnings go away
        (void)ros_msg;
        static_assert(dependent_false<CAN_MSG_TYPE>::value, "No transcoder was generated for the provided ROS message type");
    }

    /**
	 * Maps a C CAN message type to its corresponding pack function.
	 * If a message type not generated by ros2_j1939_babbler_msgs is provided, compilation will be blocked.
     * @tparam C CAN message type to pack
     * @param dst_p destination buffer to pack into
     * @param src_p instance of the C CAN message to pack up
	 * @param size size of dst_p
	 */
    template<typename CAN_MSG_TYPE>
    int pack_can_message(uint8_t* dst_p, const CAN_MSG_TYPE* src_p, size_t size)
    {
      	(void)dst_p;
        (void)src_p;
        (void)size;
        static_assert(dependent_false<CAN_MSG_TYPE>::value, "No pack function was mapped for the provided CAN message type");
        *dst_p = 0;  // Make "can be const" warning go away (no segfault because static_assert fails compilation)
        return -1;
    }

    /**
     * Maps a C CAN message type to its corresponding unpack function.
     * If a message type not generated by ros2_j1939_babbler_msgs is provided, compilation will be blocked.
     * @tparam C CAN message type to pack
     * @param dst_p instance of the C CAN message to unpack to
     * @param src_p source buffer to unpack from
     * @param size size of src_p
     */
    template<typename CAN_MSG_TYPE>
    int unpack_can_message(CAN_MSG_TYPE* dst_p, const uint8_t* src_p, size_t size)
    {
        (void)dst_p;
        (void)src_p;
        (void)size;
        static_assert(dependent_false<CAN_MSG_TYPE>::value, "No unpack function was mapped for the provided CAN message type");
        *dst_p = 0;  // Make "can be const" warning go away (no segfault because static_assert fails compilation)
        return -1;
    }

    /**
     * Generates and publishes a ROS message of the provided type using a map of J1939 signal names to their values.
     * If a message type not generated by ros2_j1939_babbler_msgs is provided, compilation will be blocked.
     * @tparam PGN J1939 PGN of the message type to transcode
     * @param publisher ROS publisher instance to publish with
     * @param can_msg CAN message instance to transcode
     * @param src_addr source address that the J1939 message was received from
     */
    template<uint32_t PGN>
    void buildAndPublishRos(rclcpp::Publisher<typename pgn_ros_message_type_map<PGN>::type>& publisher, std::unique_ptr<can_msgs::msg::Frame> can_msg, const uint8_t src_addr)
    {
        using C_CAN_MSG_TYPE =  typename pgn_can_message_type_map<PGN>::type;
        using ROS_MSG_TYPE = typename pgn_ros_message_type_map<PGN>::type;
        const uint8_t dlc = pgn_dlc_map<PGN>::value;
        auto ros_msg = std::make_unique<ROS_MSG_TYPE>();

        if (can_msg->dlc != dlc) {
            throw std::out_of_range(
                (std::ostringstream() << "Received CAN message with invalid length\n"
                 << "Expected: " << static_cast<int>(dlc) << "\n"
                 << "Received message: " << can_msgs::msg::to_yaml(*can_msg)
                ).str());
        }

        ros_msg->header = std::move(can_msg->header);
        ros_msg->src_addr = src_addr;

        C_CAN_MSG_TYPE c_can_msg;
        unpack_can_message<C_CAN_MSG_TYPE>(&c_can_msg, can_msg->data.data(), dlc);
        populateRos(*ros_msg, c_can_msg);
        publisher.publish(std::move(ros_msg));
    }

    /**
    * Encodes and publishes a CAN message from a ROS message of the provided type.
    * If a message type not generated by ros2_j1939_babbler_msgs is provided, compilation will be blocked.
    * @tparam PGN J1939 PGN of the message type to transcode
    * @param publisher ROS publisher instance to publish with
    * @param ros_msg ROS message instance to transcode
    * @param source_address J1939 source address to publish with
    */
    template<uint32_t PGN>
    void buildAndPublishCan(rclcpp::Publisher<can_msgs::msg::Frame>& publisher, std::unique_ptr<typename pgn_ros_message_type_map<PGN>::type> ros_msg, const uint8_t source_address)
    {
      	using C_CAN_MSG_TYPE =  typename pgn_can_message_type_map<PGN>::type;
        using ROS_MSG_TYPE = typename pgn_ros_message_type_map<PGN>::type;
        auto ros_can_msg = std::make_unique<can_msgs::msg::Frame>();
        ros_can_msg->id = PGN | source_address;
        ros_can_msg->is_extended = true;
        ros_can_msg->is_error = false;
        ros_can_msg->is_rtr = false;
        ros_can_msg->dlc = pgn_dlc_map<PGN>::value;
        C_CAN_MSG_TYPE c_can_msg;
        populateCan<C_CAN_MSG_TYPE, ROS_MSG_TYPE>(c_can_msg, *ros_msg);
        pack_can_message<C_CAN_MSG_TYPE>(ros_can_msg->data.data(), &c_can_msg, ros_can_msg->dlc);
        ros_can_msg->header = std::move(ros_msg->header);
        publisher.publish(std::move(ros_can_msg));
    }

    // Use loop, evaluated at compile time, to find index in storage tuple of a given PGN
    /**
     * Determines the index of a certain PGN within a list of PGNs.
     * This is useful to find a PGN's associated value in an n-tuple built co-indexed with the list of PGNs, such as
     *      the DispatchTable_T::storage_t tuple alias.
     * Blocks compilation if a PGN is supplied which is not in the list.
     * @tparam PGN the one to search for
     * @tparam PGNs list of PGNs to search in
     */
    template<uint32_t PGN, uint32_t... PGNs>
    constexpr std::size_t index_of() {
        constexpr uint32_t arr[] = {PGNs...};
        for (std::size_t i = 0; i < sizeof...(PGNs); ++i)
        {
            if (arr[i] == PGN) { return i; }
        }
        static_assert(sizeof...(PGNs) > 0, "PGN not found in list of known PGNs");
        return 0;
    }

    /**
     * Class holding an rclcpp::Publisher for each of the ROS message types associated with the provided list of PGNs.
     * Mappings are computed at compile time, and dispatch<my_pgn>(...) can be used to publish a messsage of the type
     *      associated with PGN my_pgn.
     * If types are not known at compile time, runtime_dispatch(my_pgn, ...) can be used to efficiently select the
     *      correct dispatch function and publish a message of the type associated with PGN my_pgn.
     * @tparam PGNs list of PGNs to generate the dispatch table for
     */
    template<uint32_t... PGNs>
    class DispatchTable_T {
    public:
        /**
         * Construct an instance of the dispatch table, creating all the ROS publishers needed to dispatch messages.
         * @param node pointer to the ROS node to create publishers under
         * @param device_id source address to use for published J1939 messages
         * @param topic_prefix string to prepend to all message topic names, not including the '/' between
         * @param transmitter_topic topic to publish CAN messages to, will not have topic_prefix prepended
         * @param qos_history_depth history depth to create publishers with
         */
        DispatchTable_T(rclcpp::Node* node,  const uint8_t device_id, const std::string& topic_prefix, const std::string& transmitter_topic, const size_t qos_history_depth)
            : device_id_{device_id},
              publishers_{createPublishers(node, topic_prefix, qos_history_depth)},
              can_publisher_{createTransmitter(node, transmitter_topic, qos_history_depth)}
        {
          subscribers_ = createSubscribers(node, topic_prefix, qos_history_depth);
        }

        /**
         * Dynamically select the correct dispatch function and publish a message of the type associated with the provided PGN.
         * @param pgn J1939 PGN of the message to publish
         * @param can_msg CAN message instance to transcode
         * @param src_addr source address that the J1939 message was received from
         */
        void runtime_dispatch(const uint32_t pgn, std::unique_ptr<can_msgs::msg::Frame> can_msg, const uint8_t src_addr)
        {
            // Fold expression will expand into a giant switch
            bool handled = ((pgn == PGNs ? (dispatch<PGNs>(std::move(can_msg), src_addr), true) : false) || ...);
            (void)handled; // May want to use this for logging or something in the future
        }

        /*
        // Alternatively could use table for runtime dispatch
        using func_t = void(*)(DispatchTable_T&)
        static constexpr func_t table[] = {
            [](DispatchTable& self) { self.template dispatch<PGNs>(); }...
        };
        */

        /**
         * Publish a ROS message of the type associated with the provided PGN.
         * @tparam PGN J1939 PGN of the message to publish
         * @param can_msg CAN message instance to transcode
         * @param src_addr source address that the J1939 message was received from
         */
        template<uint32_t PGN>
        void dispatch(std::unique_ptr<can_msgs::msg::Frame> can_msg, const uint8_t src_addr)
        {
            constexpr std::size_t index = index_of<PGN, PGNs...>();
            auto& publisher = std::get<index>(publishers_);
            buildAndPublishRos<PGN>(*publisher, std::move(can_msg), src_addr);
        }

    private:
        /**
         * Alias for the type of the massive n-tuple used to store the different ROS publishers (each a different type).
         * We basically use the tuple like an array holding objects of different types in a type-safe manner, since
         *      compilation would be blocked if types didn't match.
         */
        using publisher_storage_t = std::tuple<std::shared_ptr<rclcpp::Publisher<typename pgn_ros_message_type_map<PGNs>::type>>...>;
        using subscriber_storage_t = std::tuple<std::shared_ptr<rclcpp::Subscription<typename pgn_ros_message_type_map<PGNs>::type>>...>;

        /**
         * Source address to publish with.
         */
        uint8_t device_id_;

        /**
         * Instance of n-tuple storing all the different ROS publishers.
         */
        publisher_storage_t publishers_;

        /**
         * Instance of n-tuple storing all the different ROS publishers.
         */
        subscriber_storage_t subscribers_;

        /**
         * Publisher to transmit outgoing CAN messages with.
         */
        std::shared_ptr<rclcpp::Publisher<can_msgs::msg::Frame>> can_publisher_;

        /**
         * Helper function to create a ROS publisher from the provided PGN.
         * @tparam PGN J1939 PGN associated with the ROS message type to create the publisher for
         * @param node pointer to the ROS node to create publishers under
         * @param topic_prefix string to prepend to all message topic names, not including the '/' between
         * @param qos_history_depth history depth to create publishers with
         */
        template<uint32_t PGN>
        static std::shared_ptr<rclcpp::Publisher<typename pgn_ros_message_type_map<PGN>::type>> makePublisher(rclcpp::Node* node, const std::string& topic_prefix, const size_t qos_history_depth)
        {
            using MSG_TYPE = typename pgn_ros_message_type_map<PGN>::type;
            return node->create_publisher<MSG_TYPE>((std::ostringstream() << topic_prefix << '/' << message_type_name_map<MSG_TYPE>::name).str(), qos_history_depth);
        }

        /**
         * Helper function to create and populate the publisher storage tuple.
         * Expands/unpacks the list of PGNs to add to the storage tuple.
         * I.e. iterates through the list of PGNs creating a publisher and appending it to the storage tuple initialisation list
         * Note that this is evaluated at compile time, it is simply one giant pre-determined make_tuple call at runtime.
         * @param node pointer to the ROS node to create publishers under
         * @param topic_prefix string to prepend to all message topic names, not including the '/' between
         * @param qos_history_depth history depth to create publishers with
         */
        static publisher_storage_t createPublishers(rclcpp::Node* node, const std::string& topic_prefix, const size_t qos_history_depth)
        {
            return std::make_tuple(makePublisher<PGNs>(node, topic_prefix, qos_history_depth)...);
        }

        /**
         * Helper function to create a ROS publisher from the provided PGN.
         * @tparam PGN J1939 PGN associated with the ROS message type to create the publisher for
         * @param node pointer to the ROS node to create publishers under
         * @param topic_prefix string to prepend to all message topic names, not including the '/' between
         * @param qos_history_depth history depth to create publishers with
         */
        template<uint32_t PGN>
        std::shared_ptr<rclcpp::Subscription<typename pgn_ros_message_type_map<PGN>::type>> makeSubscriber(rclcpp::Node* node, const std::string& topic_prefix, const size_t qos_history_depth)
        {
            using MSG_TYPE = typename pgn_ros_message_type_map<PGN>::type;
            return node->create_subscription<MSG_TYPE>(
                (std::ostringstream() << topic_prefix << '/' << message_type_name_map<MSG_TYPE>::name << "/tx").str(),
                qos_history_depth,
                [this](std::unique_ptr<MSG_TYPE> msg) { buildAndPublishCan<PGN>(*this->can_publisher_, std::move(msg), device_id_);}
            );
        }

        /**
         * Helper function to create and populate the subscriber storage tuple.
         * Expands/unpacks the list of PGNs to add to the storage tuple.
         * I.e. iterates through the list of PGNs creating a publisher and appending it to the storage tuple initialisation list
         * Note that this is evaluated at compile time, it is simply one giant pre-determined make_tuple call at runtime.
         * @param node pointer to the ROS node to create subscribers under
         * @param topic_prefix string to prepend to all message topic names, not including the '/' between
         * @param qos_history_depth history depth to create publishers with
         */
        subscriber_storage_t createSubscribers(rclcpp::Node* node, const std::string& topic_prefix, const size_t qos_history_depth)
        {
            return std::make_tuple(makeSubscriber<PGNs>(node, topic_prefix, qos_history_depth)...);
        }

        static std::shared_ptr<rclcpp::Publisher<can_msgs::msg::Frame>> createTransmitter(rclcpp::Node* node, const std::string& transmitter_topic, const size_t qos_history_depth)
        {
            return node->create_publisher<can_msgs::msg::Frame>(transmitter_topic, qos_history_depth);
        }
    };
} // namespace ros2_j1939_babbler_msgs

#endif //ROS2_J1939_BABBLER_MSGS__TYPE_CONVERSION_HELPERS_HPP_
