/*
 * Copyright 2026 University of Manitoba Robotics Team
 * Noah Reeder
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef ROS2_J1939_BABBLER_MSGS__TYPE_CONVERSION_HELPERS_HPP_
#define ROS2_J1939_BABBLER_MSGS__TYPE_CONVERSION_HELPERS_HPP_

#include <type_traits>
#include <string>
#include <unordered_map>
#include <memory>

#include <cassert>
#include <cstdint>

#include <rclcpp/rclcpp.hpp>
#include <std_msgs/msg/header.hpp>

namespace ros2_j1939_babbler_msgs
{
    /**
     * Need this to prevent compiler from automatically instantiating primary `populate` template and hitting the static_assert
     * @tparam T dummy
     */
    template<typename T>
    struct dependent_false : std::false_type {};

    // Default type conversion, throws a compile-time error because we are expecting template to be specialised for known messages
    /**
     * Generates a ROS message of the provided type using a map of J1939 signal names to their values.
     * If a message type not generated by ros2_j1939_babbler_msgs is provided, compilation will be blocked.
     * @tparam MSG_TYPE ROS message type to populate
     * @param fields dictionary holding signal values, keyed by signal name in DBC
     * @param header std_msgs::msg::Header to send with this message
     * @param src_addr source address that the J1939 message fields is derived from was received from
     */
    template<typename MSG_TYPE>
    void populate(MSG_TYPE& msg, const std::unordered_map<std::string, double>& fields)
    {
        (void)msg; // Make unused parameter warnings go away
        (void)fields;
        static_assert(dependent_false<MSG_TYPE>::value, "No type conversion was generated for the provided ROS message type");
    }

    /**
     * Generates and publishes a ROS message of the provided type using a map of J1939 signal names to their values.
     * If a message type not generated by ros2_j1939_babbler_msgs is provided, compilation will be blocked.
     * @tparam MSG_TYPE ROS message type to publish
     * @param publisher ROS publisher instance to publish with
     * @param fields dictionary holding signal values, keyed by signal name in DBC
     * @param header std_msgs::msg::Header to send with this message
     * @param src_addr source address that the J1939 message fields is derived from was received from
     */
    template<typename MSG_TYPE>
    void buildAndPublish(rclcpp::Publisher<MSG_TYPE>& publisher, const std::unordered_map<std::string, double>& fields, std_msgs::msg::Header header, const uint8_t src_addr)
    {
        auto msg = std::make_unique<MSG_TYPE>();
        msg->header = std::move(header);
        msg->src_addr = src_addr;
        populate(*msg, fields);
        publisher.publish(std::move(msg));
    }

    /**
     * Maps PGNs to ROS message types.
     * @tparam PGN J1939 PGN to look up
     */
    template<uint32_t PGN> struct pgn_message_type_map;

    /**
     * Maps ROS message types to the message type as a string.
     * @tparam MSG_TYPE ROS type to stringify
     */
    template<typename MSG_TYPE> struct message_type_name_map;

    // Use loop, evaluated at compile time, to find index in storage tuple of a given PGN
    /**
     * Determines the index of a certain PGN within a list of PGNs.
     * This is useful to find a PGN's associated value in an n-tuple built co-indexed with the list of PGNs, such as
     *      the DispatchTable_T::storage_t tuple alias.
     * Blocks compilation if a PGN is supplied which is not in the list.
     * @tparam PGN the one to search for
     * @tparam PGNs list of PGNs to search in
     */
    template<uint32_t PGN, uint32_t... PGNs>
    constexpr std::size_t index_of() {
        constexpr uint32_t arr[] = {PGNs...};
        for (std::size_t i = 0; i < sizeof...(PGNs); ++i)
        {
            if (arr[i] == PGN) { return i; }
        }
        static_assert(sizeof...(PGNs) > 0, "PGN not found in list of known PGNs");
        return 0;
    }

    /**
     * Class holding an rclcpp::Publisher for each of the ROS message types associated with the provided list of PGNs.
     * Mappings are computed at compile time, and dispatch<my_pgn>(...) can be used to publish a messsage of the type
     *      associated with PGN my_pgn.
     * If types are not known at compile time, runtime_dispatch(my_pgn, ...) can be used to efficiently select the
     *      correct dispatch function and publish a message of the type associated with PGN my_pgn.
     * @tparam PGNs list of PGNs to generate the dispatch table for
     */
    template<uint32_t... PGNs>
    class DispatchTable_T {
    public:
        /**
         * Construct an instance of the dispatch table, creating all the ROS publishers needed to dispatch messages.
         * @param node pointer to the ROS node to create publishers under
         * @param topic_prefix string to prepend to all message topic names, not including the '/' between
         * @param qos_history_depth history depth to create publishers with
         */
        DispatchTable_T(rclcpp::Node* node, const std::string& topic_prefix, const size_t qos_history_depth)
            : publishers_{createPublishers(node, topic_prefix, qos_history_depth)}
        {}

        /**
         * Dynamically select the correct dispatch function and publish a message of the type associated with the provided PGN.
         * @param pgn J1939 PGN of the message to publish
         * @param fields dictionary holding signal values, keyed by signal name in DBC
         * @param header std_msgs::msg::Header to send with this message
         * @param src_addr source address that the J1939 message fields is derived from was received from
         */
        void runtime_dispatch(const uint32_t pgn, const std::unordered_map<std::string, double>& fields, std_msgs::msg::Header header, const uint8_t src_addr)
        {
            bool handled = ((pgn == PGNs ? (dispatch<PGNs>(fields, std::move(header), src_addr), true) : false) || ...); // Fold expression will expand into a giant switch
            assert(handled);
        }

        /*
        // Alternatively could use table for runtime dispatch
        using func_t = void(*)(DispatchTable_T&)
        static constexpr func_t table[] = {
            [](DispatchTable& self) { self.template dispatch<PGNs>(); }...
        };
        */

        /**
         * Publish a ROS message of the type associated with the provided PGN.
         * @tparam PGN J1939 PGN of the message to publish
         * @param fields dictionary holding signal values, keyed by signal name in DBC
         * @param header std_msgs::msg::Header to send with this message
         * @param src_addr source address that the J1939 message fields is derived from was received from
         */
        template<uint32_t PGN>
        void dispatch(const std::unordered_map<std::string, double>& fields, std_msgs::msg::Header header, const uint8_t src_addr) {
            constexpr std::size_t index = index_of<PGN, PGNs...>();
            auto& publisher = std::get<index>(publishers_);
            buildAndPublish<typename pgn_message_type_map<PGN>::type>(*publisher, fields, std::move(header), src_addr);
        }

    private:
        /**
         * Alias for the type of the massive n-tuple used to store the different ROS publishers (each a different type).
         * We basically use the tuple like an array holding objects of different types in a type-safe manner, since
         *      compilation would be blocked if types didn't match.
         */
        using storage_t = std::tuple<std::shared_ptr<rclcpp::Publisher<typename pgn_message_type_map<PGNs>::type>>...>;

        /**
         * Instance of n-tuple storing all the different ROS publishers.
         */
        storage_t publishers_;

        /**
         * Helper function to create a ROS publisher from the provided PGN.
         * @tparam PGN J1939 PGN associated with the ROS message type to create the publisher for
         * @param node pointer to the ROS node to create publishers under
         * @param topic_prefix string to prepend to all message topic names, not including the '/' between
         * @param qos_history_depth history depth to create publishers with
         */
        template<uint32_t PGN>
        static std::shared_ptr<rclcpp::Publisher<typename pgn_message_type_map<PGN>::type>> makePublisher(rclcpp::Node* node, const std::string& topic_prefix, const size_t qos_history_depth)
        {
            using MSG_TYPE = typename pgn_message_type_map<PGN>::type;
            return node->create_publisher<MSG_TYPE>((std::ostringstream() << topic_prefix << '/' << message_type_name_map<MSG_TYPE>::name).str(), qos_history_depth);
        }

        /**
         * Helper function to create and populate the publisher storage tuple.
         * Expands/unpacks the list of PGNs to add to the storage tuple.
         * I.e. iterates through the list of PGNs creating a publisher and appending it to the storage tuple initialisation list
         * Note that this is evaluated at compile time, it is simply one giant pre-determined make_tuple call at runtime.
         * @param node pointer to the ROS node to create publishers under
         * @param topic_prefix string to prepend to all message topic names, not including the '/' between
         * @param qos_history_depth history depth to create publishers with
         */
        static storage_t createPublishers(rclcpp::Node* node, const std::string& topic_prefix, const size_t qos_history_depth)
        {
            return std::make_tuple(makePublisher<PGNs>(node, topic_prefix, qos_history_depth)...);
        }
    };
} // namespace ros2_j1939_babbler_msgs

#endif //ROS2_J1939_BABBLER_MSGS__TYPE_CONVERSION_HELPERS_HPP_
