name: Create version tag

on:
  push:
    branches:
      - develop

jobs:
  tag-version:
    uses: UMRoboticsTeam/umrt-ci-cd/.github/workflows/version-tag.yaml@main
    permissions:
        contents: write
